generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  billingAccount: bill account
  billingTeamName: team name
  gheToken: ""
  adpAccessToken: ""
projectInformation:
  projectName: My super project
  projectShortName: project_saved_in_config2134
  buildType: maven
  testInstance: true
  preprodInstance: true
  uatInstance: false
cloudService:
  awsOrAzure: eks
  deploymentLocation: aws_ew3
  acpOrCRP: acp
  displayName: awsowp
  version: ""
  productionCluster: false
  subscriptionId: ""
  enableStorageProvisioning: true
  ingressSubnetName: ""
  clusterSubnetName: ""
  adAdminGroupName: ""
  adViewerGroupName: ""
  adEditorGroupName: ""
  privateDnsZone: ""
  awsAccountId: "3213"
  instanceType: derter
  r53HostedZoneDomainName: fdsf
  sshWorkerKey: ""
  availabilityZones: ""
  az1HarmonizedSubnetId: ""
  az1WorkerSubnetId: ""
  az1PodSubnetId: ""
  az2HarmonizedSubnetId: ""
  az2WorkerSubnetId: ""
  az2PodSubnetId: ""
  az3HarmonizedSubnetId: ""
  az3WorkerSubnetId: ""
  az3PodSubnetId: ""
  workerSecurityGroupIds: ""
  ingressSecurityGroupIds: ""
  customDefinedAutomationAdminRole: ""
automationService:
  jenkinsOrGithubActions: gheactions
  jenkinsWebhook: 223466@ere4
gheOrganisation:
  organisationName: jarro06
  isNew: false
testingTools:
  sonarQube: true
